#!/usr/bin/env python3
"""gen_mocs.py: regenerate Maps of Content from note frontmatter.

Replaces hand-curated MOCs and Dataview dashboards with derived, validated
notes. Scans every note's frontmatter, groups by domain, and writes one MOC
per domain plus a home MOC, all in 80-moc/. Output passes validate_auxmem.py.

Run after material edits, from a git hook, or in CI. Idempotent.

Usage: gen_mocs.py [--check]
  --check: exit 1 if regeneration would change any MOC (for CI drift detection)

Requires: PyYAML.
"""

import json
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

import yaml

SCRIPT_DIR = Path(__file__).resolve().parent
AUXMEM_ROOT = SCRIPT_DIR.parent
CONFIG = json.loads((SCRIPT_DIR / "auxmem.config.json").read_text(encoding="utf-8"))
DOMAINS = CONFIG["domains"]                     # folder -> domain slug
SKIP = set(CONFIG.get("skip_dirs", [])) | {"80-moc", "00-inbox", "05-sources"}
MOC_DIR = AUXMEM_ROOT / "80-moc"
TODAY = datetime.now(timezone.utc).strftime("%Y-%m-%d")


def read_fm(path):
    text = path.read_text(encoding="utf-8", errors="replace")
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    if end < 0:
        return None
    try:
        fm = yaml.safe_load(text[3:end])
        return fm if isinstance(fm, dict) else None
    except yaml.YAMLError:
        return None


def collect():
    by_domain = defaultdict(list)
    for p in sorted(AUXMEM_ROOT.rglob("*.md")):
        rel = p.relative_to(AUXMEM_ROOT)
        if rel.parts[0] in SKIP:
            continue
        fm = read_fm(p)
        if not fm or not fm.get("domain"):
            continue
        by_domain[fm["domain"]].append((rel, fm))
    return by_domain


def moc_body(title, summary, domain, entries):
    lines = [
        "---",
        f"title: {title}",
        f"summary: {summary}",
        "type: moc",
        "status: active",
        f"domain: {domain}",
        f"created: {TODAY}",
        f"updated: {TODAY}",
        "---",
        "",
        "<!-- GENERATED by .scripts/gen_mocs.py. Do not edit by hand; edits are overwritten. -->",
        "",
    ]
    by_type = defaultdict(list)
    for rel, fm in entries:
        by_type[fm.get("type", "reference")].append((rel, fm))
    for typ in sorted(by_type):
        lines.append(f"## {typ}")
        lines.append("")
        for rel, fm in sorted(by_type[typ], key=lambda e: str(e[0])):
            href = _relpath(rel)
            status = fm.get("status", "")
            flag = "" if status == "active" else f" ({status})"
            lines.append(f"- [{fm.get('title', rel.stem)}]({href}){flag}: {fm.get('summary','').strip()}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _relpath(rel):
    import os
    return os.path.relpath(AUXMEM_ROOT / rel, start=MOC_DIR).replace("\\", "/").replace(" ", "%20")


def home_body(domain_files, home_domain):
    lines = [
        "---",
        "title: Home MOC",
        "summary: Top-level map of content linking every domain map in this auxmem. Agent entry point after AGENTS.md.",
        "type: moc", "status: active", f"domain: {home_domain}",
        f"created: {TODAY}", f"updated: {TODAY}", "---", "",
        "<!-- GENERATED by .scripts/gen_mocs.py. Do not edit by hand; edits are overwritten. -->",
        "",
        "## domain maps", "",
    ]
    for domain, fname in sorted(domain_files.items()):
        lines.append(f"- [{domain}]({fname})")
    lines.append("")
    return "\n".join(lines) + "\n"


def main(argv):
    check = "--check" in argv
    if not DOMAINS:
        if check:
            print("MOCs skipped: no domains configured.")
            return 0
        print("skipped MOC generation: no domains configured (run auxmem-init first).")
        return 0
    by_domain = collect()
    domain_files = {}
    planned = {}

    for folder, domain in DOMAINS.items():
        entries = by_domain.get(domain, [])
        fname = f"{domain}-moc.md"
        summary = (
            f"Generated map of content for the {domain} domain. "
            f"{len(entries)} note(s), grouped by type. Rebuilt by gen_mocs.py."
        )
        planned[MOC_DIR / fname] = moc_body(f"{domain} MOC", summary, domain, entries)
        domain_files[domain] = fname

    home_domain = next(iter(DOMAINS.values()))
    planned[MOC_DIR / "home-moc.md"] = home_body(domain_files, home_domain)

    # prune orphaned MOCs from domains removed from config
    valid_moc_names = {p.name for p in planned}
    orphans = []
    if MOC_DIR.exists():
        for existing in MOC_DIR.glob("*-moc.md"):
            if existing.name not in valid_moc_names:
                orphans.append(existing.relative_to(AUXMEM_ROOT))
                if not check:
                    existing.unlink()

    changed = []
    for path, content in planned.items():
        old = path.read_text(encoding="utf-8") if path.exists() else None
        if old != content:
            changed.append(path.relative_to(AUXMEM_ROOT))
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8")

    if check:
        if changed or orphans:
            print("MOCs out of date. Run gen_mocs.py:")
            for c in changed:
                print(f"  - changed: {c}")
            for o in orphans:
                print(f"  - orphan:  {o}")
            return 1
        print("MOCs up to date.")
        return 0
    print(f"generated {len(planned)} MOC(s); {len(changed)} changed; {len(orphans)} orphan(s) pruned.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
